{"name": "test_abc_002", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <test_001.Test_Abc object at 0x106167950>\n\n    @allure.severity(allure.severity_level.TRIVIAL)\n    def test_abc_002(self):\n        allure.attach(\"这是第二个一个描述\",\"试一下2\")\n>       assert 0\nE       assert 0\n\nscripts/test_001.py:20: AssertionError"}, "attachments": [{"name": "试一下2", "source": "80b0642b-28a3-439f-834f-56303d6920ec-attachment.attach"}], "start": 1588763277312, "stop": 1588763277313, "uuid": "fd8a2856-33bb-4661-a442-40bd18d77537", "historyId": "2d73cbc659e27cd6afec33799f6d4c3a", "testCaseId": "c62d198d12c966461e8ec62ea932140b", "fullName": "scripts.test_001.Test_Abc#test_abc_002", "labels": [{"name": "severity", "value": "trivial"}, {"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_001"}, {"name": "subSuite", "value": "Test_Abc"}, {"name": "host", "value": "localhost"}, {"name": "thread", "value": "5466-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_001"}]}